# Generated by Django 5.2.1 on 2025-05-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidate_profile_picture_recruiter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
