# Generated by Django 5.2 on 2025-05-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default='Nom', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='Prénom', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
    ]
