# Generated by Django 5.2 on 2025-05-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
